#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 275

#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 600000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "3wWzq/MaJKVN"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

